spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rest
    username: root
    password: jjangwoo
  hikari:
    auto-commit: false
    connection-timeout: 3000
    max-lifetime: 1800000
    maximum-pool-size: 5
    data-source-properties:
      cachePrepStmts: true
      rewriteBatchedStatements: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
    show-sql: true
    hibernate:
      dialect:
        storage_engine: innodb
      format_sql: true
      ddl-auto: update

logging:
  level:
    root: INFO
    org.rest: DEBUG


server:
  port: 8080


